POST http://localhost:8080/api/v1/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzg4NzMxODcsImV4cCI6MTc0MTU1MTU4N30.75Y46HFb-2hIkxIKFSbpinNxDbgZEbKLPfEdieub1ow
Content-Type: application/json

{
    "name": "Iron Flame - The Empyrean (Paperback genre)",
    "description": "Violet (aka Violence) Sorrengail is still flying high on her mighty - and mightily sarcastic - dragon... levels of fighting, rebelliousness and all-round sexiness are still sky-high - Daily Mail",
    "publicationYear": 2024,
    "authors": [
        {
            "fullName": "Rebecca Yarros"
        }
    ],
    "genres": [
        {
            "name": "Fantasy"
        },
        {
            "name": "Romance"
        }
    ]
}